### ISSUE TITLE
标点符号的处理

### ISSUE THREAD

**Issue by pengruifei** [BlindingDark/rime-easy-en#10]
英文的标点符号与上一个单词之间不能空格，应该紧挨着上一个单词。现在的easy-en输出的标点符号仍然被当作普通单词那样处理了，请问可以改进一下吗？
例如现在的easy-en输出：
```
I love easy english . I love rime . 
```
能否改成：
```
I love easy english. I love rime. 
```
即自动让标点紧挨着上一个单词，但是该标点的后面仍然接着一个空格。

**Comment by BlindingDark** [comment]
标点符号是在上屏完毕之后才输入的吧，如果是这种情况是无法控制的，因为空格已经上屏了没办法再处理了。

**Comment by BlindingDark** [comment]
目前英文标点直接上屏这块还没做好，稍后我会发布一个更新，使得输入标点可以直接上屏。

**Comment by pengruifei** [comment]
谢谢您的回答。那能不能在输入标点符号的时候，再用lua脚本来输出Backspace按键来删除已经上屏的空格呢？ pengruifei 邮箱：pengruifei@aliyun.com 签名由 网易邮箱大师 定制 在2020年05月18日 20:38，我没有抓狂 写道： 目前英文标点直接上屏这块还没做好，稍后我会发布一个更新，使得输入标点可以直接上屏。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BlindingDark** [comment]
> lua脚本来输出Backspace按键

rime 的 lua 脚本只能控制 rime 的行为，（据我所知应该）是无法直接控制键盘输入的。

**Comment by BlindingDark** [comment]
@pengruifei 新版本可以直接输入英文标点了

**Comment by amorphobia** [comment]
> @pengruifei 新版本可以直接输入英文标点了

我今天安装了这个方案，并且打开了 lua 脚本，好像按下标点还是会加空格呀？

**Comment by BlindingDark** [comment]
@amorphobia 是的，只是能直接输入英文标点了，但是不会去掉前面的空格。
