### ISSUE TITLE
无法弹出候选项

### ISSUE THREAD

**Issue by SpingHigh** [BlindingDark/rime-easy-en#12]
系统win10_1903，rime版本0.14.3。linux无此问题。

**Comment by BlindingDark** [comment]
Windows 和 Linux 的配置完全一样么，是否使用了 lua 扩展？是单独作为英文输入法使用，还是混合别的输入法使用？
我这里没有 Windows 环境，没办法测试，你可以先自行做最小化的配置，看看是哪里出了问题。

**Comment by SpingHigh** [comment]
谢谢回复。
我的配置很少，仅在default文件添加schame，只用了schame和dict文件，未做lua扩展，仅与系统自带英文输入混合使用。用另外一个英文输入schame “20k_en”是正常的。

**Comment by BlindingDark** [comment]
> 与系统自带英文输入混合使用

我的意思是与别的 rime 方案做中英混输么？

需要别的 Windows 用户帮忙复现一下

**Comment by SpingHigh** [comment]
没有设置中英文混输。
我的两台windows10都是这样。其中一台是用程序自带的输入法设置程序添加的easy_en，另一台是直接复制dict和schame文件，然后在default文件添加的schame，只有这些操作，没有任何其他操作。

**Comment by SpingHigh** [comment]
以下是default设置文件，其他文件除了修改sync文件夹均是默认，没有改动。
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Tue Jun 30 21:54:18 2020"
  rime_version: 1.5.3
patch:
  "ascii_composer/switch_key":
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Shift_L: commit_code
    Shift_R: commit_code
  "menu/page_size": 9
  schema_list:
    - {schema: luna_pinyin_simp}
    - {schema: easy_en}
  "switcher/hotkeys":
    - "Control+grave"
周围没有人用rime，无法找他们复现，抱歉。

**Comment by BlindingDark** [comment]
@SpingHigh 可能是 Windows 配置文件的结构略有不同，先等等看别人有没有也来报告类似问题吧。

**Comment by flytigerzhang** [comment]
我这边也是同样，最小配置，仅下载了3个文件，放在相应的地方，然后在default里增加了easy_en方案，调用该方案后，无联想出来，检查build文件夹下面未生成bin等文件，不知是否与这个有关

**Comment by flytigerzhang** [comment]
看了日志，看起来未能编译出词典bin
`I0930 22:25:01.169796 16076 engine.cc:71] starting engine.
I0930 22:25:01.169796 16076 engine.cc:126] updated option: full_shape
W0930 22:25:01.169796 16076 punctuator.cc:32] missing punctuation mapping.
I0930 22:25:01.169796 16076 engine.cc:126] updated option: _auto_commit
W0930 22:25:01.169796 16076 punctuator.cc:32] missing punctuation mapping.
I0930 22:25:01.169796 16076 dictionary.cc:261] loading dictionary 'easy_en'.
I0930 22:25:01.169796 16076 table.cc:299] loading table file: C:\Users\xxx\AppData\Roaming\Rime\build/easy_en.table.bin
E0930 22:25:01.169796 16076 mapped_file.cc:112] attempt to open non-existent file 'C:\Users\xxx\AppData\Roaming\Rime\build/easy_en.table.bin'.
E0930 22:25:01.169796 16076 table.cc:305] Error opening table file 'C:\Users\xxx\AppData\Roaming\Rime\build/easy_en.table.bin'.
E0930 22:25:01.169796 16076 dictionary.cc:263] Error loading table for dictionary 'easy_en'.
W0930 22:25:01.170795 16076 punctuator.cc:32] missing punctuation mapping.`

**Comment by BlindingDark** [comment]
发现 Windows 下 lua 的行为和 Linux 不一样，如果不加载对应的 lua 函数就会罢工。我先在 readme 里写上如何手动关闭 lua，再想想有没有更好的方法。

**Comment by BlindingDark** [comment]
@SpingHigh 尝试按此办法手动关闭连续输入增强功能

https://github.com/BlindingDark/rime-easy-en#%E4%B8%8D%E4%BD%BF%E7%94%A8%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5%E5%A2%9E%E5%BC%BA
