### ISSUE TITLE
win10下如何配置中英混输？

### ISSUE THREAD

**Issue by victorzhao** [BlindingDark/rime-easy-en#13]
在win10下，没法通过rime-install的方式进行中英混输，不知道如果手动配置改如何设置？

**Comment by VimWei** [comment]
很需要这个详细教程！期待

**Comment by VimWei** [comment]
能否说说以下命令具体做了什么修改，以便我们可以借鉴用于手动修订win下的配置：

`bash rime-install BlindingDark/rime-easy-en:customize:schema=luna_pinyin`

**Comment by VimWei** [comment]
看文档猜测：修订对应方案的custom文件，加入以下代码？

# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
  - patch/+:
      __include: easy_en:/patch
# }

**Comment by VimWei** [comment]
我做了如下实验，没有成功（无法混输，单独使用Easy English 也不能弹出提示词）：

1.  在 double_pinyin_flypy.custom.yaml 中添加

```
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
  - patch/+:
      __include: easy_en:/patch
# }
```

2. 在 default.custom.yaml 添加：

```
  schema_list:
    - {schema: double_pinyin_flypy}
    - {schema: luna_pinyin_simp}
    - {schema: easy_en}

```

3. 在配置文件夹加入如下文件：
easy_en.yaml easy_en.dict.yaml easy_en.schema.yaml
或者 customize.recipe.yaml easy_en.yaml easy_en.dict.yaml easy_en.schema.yaml
或者  lua\easy_en.lua customize.recipe.yaml easy_en.yaml easy_en.dict.yaml easy_en.schema.yaml

**Comment by VimWei** [comment]
补充说明：我使用这里提供的2017年版的Easy English 是可是正常使用的：
* 2017年版Easy English：http://pan.baidu.com/s/1jIn1LPk
* 相应教程：https://blog.codeingboy.me/rime-customization/

只不过没有混输功能。

**Comment by VimWei** [comment]
我仅需要 混输功能，而不需要 连续输入，需要安装lua程序及相应的lua\easy_en.lua文件吗？

**Comment by BlindingDark** [comment]
@VimWei 

patch 需要在 custom 下加入

```yaml
__patch:
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
  - patch/+:
      __include: easy_en:/patch
# }

```


> 我仅需要 混输功能

```diff
  schema_list:
    - {schema: double_pinyin_flypy}
    - {schema: luna_pinyin_simp}
-   - {schema: easy_en}
```

不需要添加这个，加了这是可以切换到单独的英文输入。

> 不需要 连续输入，需要安装lua程序及相应的lua\easy_en.lua文件吗？

不需要

**Comment by VimWei** [comment]
> patch 需要在 custom 下加入
> 
> ```yaml
> __patch:
> # Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin {
>   - patch/+:
>       __include: easy_en:/patch
> # }
> ```
> 

若custom文件中已经有 `patch:`了，那么上述第一行的 `__patch:` 还要写吗？

**Comment by BlindingDark** [comment]
不需要了，加在 `__patch` 层级下即可

VimWei <notifications@github.com> 于2020年12月1日周二 上午11:02写道：

**Comment by BlindingDark** [comment]
@VimWei 你的意思是有 `patch`，不是 `__patch`？
那需要这么写

```yaml
patch:
  # 其它的配置
  __include: easy_en:/patch
```

**Comment by BlindingDark** [comment]
两种方式效果一样，只是 plum 默认使用 `__patch` 方式，减少冲突。

详细的语法可以参见
https://github.com/rime/home/wiki/Configuration#%E8%AA%9E%E6%B3%95

**Comment by VimWei** [comment]
还是无法弹出候选项，可能与这个issue有关： https://github.com/BlindingDark/rime-easy-en/issues/12

**Comment by VimWei** [comment]
终于可以了！太感谢了！

以下是我的配置文件（与Easy English有关的主要就是第三行）：


![image](https://user-images.githubusercontent.com/25874852/100693648-4b9d2e00-33c8-11eb-8c9e-50a1faf15809.png)

**Comment by BlindingDark** [comment]
@VimWei 搞了个 Windows 虚拟机试了一下。发现 Windows 下的 lua 插件行为和 Linux 不一样，Windows 下如果 lua 插件没有加载就会出问题，Linux 下则不影响其它功能的使用。暂时只能手动将 lua 过滤器去掉。我把这个先加到 readme 里，再想想有没有更好的方法。

**Comment by BlindingDark** [comment]
@victorzhao 已增加手动安装的方法

https://github.com/BlindingDark/rime-easy-en#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

**Comment by VimWei** [comment]
感谢升级readme文档！根据文档重新做了设置，现在也可以独立使用Easy English了，cool！
