### ISSUE TITLE
easy-en方案目前只有你在维护嘛？

### ISSUE THREAD

**Issue by tumuyan** [BlindingDark/rime-easy-en#14]
在readme里有写，easy_en 原作者 Patricivs。但是我看了下他的仓库没有easy_en，所以目前只有你在维护嘛

**Comment by BlindingDark** [comment]
我从网上找到的原始方案里面留有邮箱，基本确认作者是 Patricivs，不过他未将其传到 github 上。  
目前的方案和原方案区别已经很大了，我替换了原来的词库，修改了部分配置文件，支持了 plum 安装格式，以及加入了 lua 支持，算是一个新的项目了。  
目前由我维护，欢迎 PR 😘️。
