### ISSUE TITLE
怎么手动安装？

### ISSUE THREAD

**Issue by MiraculousMoon** [BlindingDark/rime-easy-en#16]
因为在用FCITX5所以没法用官方的plum
我手动安装之后的结果是这样：
![image](https://user-images.githubusercontent.com/61657399/99139290-3d35df00-2672-11eb-845b-8cef09e9463b.png)
确定已经按照提示打了patch，如图：
![image](https://user-images.githubusercontent.com/61657399/99139307-7c643000-2672-11eb-887c-0c065c29e7cc.png)
用户资料目录下的文件也复制了过来：
![image](https://user-images.githubusercontent.com/61657399/99139321-94d44a80-2672-11eb-8404-5657e85641c2.png)
同时也有lua目录：
![image](https://user-images.githubusercontent.com/61657399/99139335-b1708280-2672-11eb-9b7d-cd7fc62feeed.png)

**Comment by BlindingDark** [comment]
有没有配置 `rime.lua` 文件呢？具体做法可以参考[这里](https://github.com/BlindingDark/rime-easy-en#%E5%AE%89%E8%A3%85%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5%E5%A2%9E%E5%BC%BA%E5%8A%9F%E8%83%BD)

**Comment by MiraculousMoon** [comment]
> 有没有配置 `rime.lua` 文件呢？具体做法可以参考[这里](https://github.com/BlindingDark/rime-easy-en#%E5%AE%89%E8%A3%85%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5%E5%A2%9E%E5%BC%BA%E5%8A%9F%E8%83%BD)

![图片](https://user-images.githubusercontent.com/61657399/99148640-d2ad8f00-26c3-11eb-8843-baee3cf4de75.png)
直接复制把代码复制过来了，应该没问题

**Comment by BlindingDark** [comment]
如果是配置没问题的话，应该是没开启 lua 扩展。你可以在系统设置界面中的 fcitx rime 设置的插件选项里手动填入 lua，尝试加载 lua 扩展。

**Comment by MiraculousMoon** [comment]
> 如果是配置没问题的话，应该是没开启 lua 扩展。你可以在系统设置界面中的 fcitx rime 设置的插件选项里手动填入 lua，尝试加载 lua 扩展。

![图片](https://user-images.githubusercontent.com/61657399/99161095-7aa97380-2729-11eb-82a7-e48b935242ca.png)

![图片](https://user-images.githubusercontent.com/61657399/99161104-8b59e980-2729-11eb-8ad2-547e94d7fd7f.png)

貌似还是不行

**Comment by BlindingDark** [comment]
你的预期效果是怎么样？自动分词加空格么？暂时还不能做到这样，每个单词还是要手动选择的，只是选择之后会加上空格。

**Comment by MiraculousMoon** [comment]
之前没有装fcitx5-lua(from Archlinux)，现在装了之后还是没有办法实现连续输入增强功能，就算是手动选择了单词还是没有办法加上空格

关于readme中去除太极图案的方法，我试过之后这项功能直接就消失了，怀疑是不是代码错了？

![图片](https://user-images.githubusercontent.com/61657399/99182315-422c8880-276f-11eb-9e97-c7671697a37c.png)

删除这行代码之后，在easy_en.custom.yaml中添加相应代码也没有作用，太极符号还在：

![图片](https://user-images.githubusercontent.com/61657399/99182393-b49d6880-276f-11eb-9e19-0dc2db226292.png)

关于log，事实上一直是这样：
![图片](https://user-images.githubusercontent.com/61657399/99182422-e0205300-276f-11eb-8ac4-90ea524d000a.png)

关于引入别的lua，还没有找到这样的项目...

**Comment by BlindingDark** [comment]
方便提供联系方式么？
你可以加 tg 群 https://t.me/loverime 找到我。

或者你有公开的配置文件地址么。

**Comment by BlindingDark** [comment]
排查之后发现是由于没有单独使用 easy_en，混输状态输入增强是不起效的。还有其它问题欢迎再提 issue。
