### ISSUE TITLE
可否介绍一下英文词库的来龙去脉

### ISSUE THREAD

**Issue by VimWei** [BlindingDark/rime-easy-en#17]
目前输入company没有提示，这应该是高频词汇。可否介绍一下现有英文词库的来龙去脉，以便我们可以自定义更多适用的词汇？

skywind3000 曾经制作了高频英文词库：[WordMax2K.zip](https://github.com/BlindingDark/rime-easy-en/files/5620606/WordMax2K.zip)

该词汇表基于coca 和 bnc 语料库，取 2w 高频词的词库，算上变形，一共 50-60k，踢掉3个字母以下的词，合计41789词。（适用背景：词频前1万也就是正常外国人的口语词汇量，连书面语都覆盖不了，英语母语的人，平均词汇量 3.5 万。覆盖常用书面语，起码 2 万的词汇量才够。）

我一直用它配合如下插件在Vim下使用，效果非常好： https://github.com/skywind3000/vim-auto-popmenu

更多专业词库： https://github.com/skywind3000/vim-dict/

**Comment by VimWei** [comment]
我知道为什么没有company的提示了，因为优先级比较低，一直在后面很多页才找到。如果直接使用Easy English就会出现在第一屏。这个中英文混合的优先级不好弄啊。

**Comment by BlindingDark** [comment]
看来这个调位置的需求还是有的啊，我把之前回答的内容整理到 readme 吧。

如何调整混输单词排序位置 https://github.com/BlindingDark/rime-easy-en/issues/9#issuecomment-623070206

词典来源也是和你说的同一个作者 https://github.com/skywind3000/ECDICT
使用该转换工具生成 https://github.com/BlindingDark/rime_easy_eng_dict
相关讨论 https://github.com/BlindingDark/rime-easy-en/issues/3

**Comment by BlindingDark** [comment]
配置方法已更新到 readme

此 issue 暂时关闭，如果有什么新的疑问欢迎继续提问😘

https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E8%8B%B1%E6%96%87%E5%8D%95%E8%AF%8D%E6%8E%92%E7%9A%84%E5%A4%AA%E9%9D%A0%E5%90%8E

**Comment by VimWei** [comment]
赞赞赞！感谢解疑！

**Comment by VimWei** [comment]
我试用了一天，感觉以下两个方面有点影响体验：

1. 对于长度小于3的英文词汇，完全没有必要进入词库。目前输入“le”，本意是想输入中文“了”，但却出现“LE”。虽然可以调整词频让其靠后，但对于这种短小的词汇，如果词频太靠后也没什么意义，还不如直接删除，减轻词库量。

2. 使用了Easy English，感觉输入时计算机运行没有那么流畅，不知道是自己的感觉有误，还是因为该词库量太大确实影响了性能。因为我会在虚拟机等低性能环境中使用，所以比较关心性能的问题。若果真如此，可否再出一版规模小一点的词库，只收入词频前2万或1万，以增强体验？

**Comment by BlindingDark** [comment]
@VimWei 你可以使用上面提供的词典转换工具自行裁剪所需要的词库，现在还没有提供命令行接口来调整筛选项目，只能通过修改代码的方式进行调整，以后可以考虑更多命令行参数方便自定义词库。

目前 easy_en 默认参数下，每页候选项 7 个，le 应该在 5 页之后。

之所以加入短词，是因为连续输入的选词只能从现有词库中选取，如果去掉短词，连续功能输入就无法正常使用了。

**Comment by VimWei** [comment]
噢，明白了！

**Comment by VimWei** [comment]
有个想法：或许可以将词库分级分类，大家按需配置加载不同的词库组合。

**Comment by BlindingDark** [comment]
@VimWei 考虑，你可以新建一个 issue 来提一下。最好附带词库的来源页面。

**Comment by VimWei** [comment]
好的
