### ISSUE TITLE
Feat: 自定义词库

### ISSUE THREAD

**Issue by VimWei** [BlindingDark/rime-easy-en#19]
目前词库只有一个，其中的词条完整性比较好，但也意味着数量比较多，这种设计会影响如下情形使用体验：

1. 若使用混拼，并将英文词汇的优先级提高（参数easy_en/initial_quality: 0.5），那么很多常见的中文高频词会被英文词汇替代，比如 “LE 了”、“DE 的”等。这主要是因为我们的词库中有大量字母小于3个的词汇。
2. 如果去掉短词，连续输入功能又无法正常使用。
3. 难以平衡全面性和精小性：词条数量太多会影响计算机的运行性能，数量太少又导致常用词汇的缺失。
4. 无法满足用户的个性化需求：不同用户有不同的个性化专业词库需求，难以穷尽。

鉴于上述原因，建议考虑将词库分级（通用性词库，可按权威词频统计信息来分级）、分类（字母长短、专业门类），并有配置参数可以让用户按需加载，更进一步则是提供相应的词库制作指引和工具，让用户可以自行定制个性化词库。

参考资料附后跟帖：
1. 词频信息
2. 专业门类

**Comment by BlindingDark** [comment]
目前计划是

1. 对于不同来源的词库建立对应独立的仓库进行维护和发布，然后在本仓库提供汇总的下载连接。
1. 提供配置向，方便用户更换，或搭配多种词库使用

词库来源应保证无版权问题，欢迎各位在此分享合适的词库。

**Comment by BlindingDark** [comment]
默认词库来自于 https://github.com/BlindingDark/rime_easy_eng_dict

**Comment by VimWei** [comment]
<h3>Word frequency词频语料库</h3>
<dl><p>
    </p><dt><a href="http://www.audiencedialogue.net/english.html" add_date="1568187535">Global English</a>
    </dt><dt><a href="https://www.pdawiki.com/forum/forum.php?mod=viewthread&amp;tid=21736&amp;highlight=%E8%AF%8D%E9%A2%91">英英学習型词典的词频标示判读心得</a>
    </dt><dt><a href="https://www.pdawiki.com/forum/forum.php?mod=viewthread&amp;tid=20533">单词释义比例词典</a>
    </dt><dt><h3 add_date="1594629314" last_modified="1594629314">Learn these words first</h3>
    <dl><p>
        </p><dt><a href="http://learnthesewordsfirst.com/">Learn These Words First</a>
        </dt><dt><a href="http://learnthesewordsfirst.com/about/what-is-a-multi-layer-dictionary.html">What is a Multi-Layer Dictionary?</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">New General Service List</h3>
    <dl><p>
        </p><dt><a href="http://www.newgeneralservicelist.org/">New General Service List</a>
        </dt><dt><a href="https://en.wikipedia.org/wiki/General_Service_List" add_date="1557114280">General Service List - Wikipedia</a>
        </dt><dt><a href="https://en.wikipedia.org/wiki/New_General_Service_List" add_date="1557114445">New General Service List - Wikipedia</a>
        </dt><dt><a href="https://quizlet.com/class/821915/" add_date="1557115080">NGSL by Frequency | Quizlet</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">COCA</h3>
    <dl><p>
        </p><dt><a href="https://www.wordfrequency.info/" add_date="1556169126">COCA Word frequency: based on 450 million word COCA corpus</a>
        </dt><dt><a href="https://www.english-corpora.org/coca/">Corpus of Contemporary American English (COCA)</a>
        </dt><dt><a href="http://www.wordfrequency.info/?freeList=y" add_date="1483854464">Word frequency: based on 450 million word COCA corpus</a>
        </dt><dt><a href="https://www.wordandphrase.info/frequencyList.asp" add_date="1554795368">COCA Frequency list::查看 60000 单词词频排名</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">BNC - British National Corpus</h3>
    <dl><p>
        </p><dt><a href="http://www.natcorp.ox.ac.uk/">[bnc] British National Corpus</a>
        </dt><dt><a href="http://bncweb.lancs.ac.uk/bncwebSignup/user/login.php">BNCweb registration - Main</a>
        </dt><dt><a href="http://www.kilgarriff.co.uk/bnc-readme.html" add_date="1521290554">BNC database and word frequency lists</a>
        </dt><dt><a href="https://www.english-corpora.org/bnc/">British National Corpus (BYU-BNC)</a>
        </dt><dt><a href="https://www.victoria.ac.nz/lals/about/staff/paul-nation" add_date="1556185854">Paul Nation Vocabulary Lists based on BNC</a>
        </dt><dt><a href="http://ucrel.lancs.ac.uk/bncfreq/">Companion Website for: Word Frequencies in Written and Spoken English</a>
        </dt><dt><a href="http://www.audiencedialogue.net/susteng.html" add_date="1568190254">BNC 15000 - Sustainable English</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">Oxford words list</h3>
    <dl><p>
        </p><dt><a href="https://www.oxfordlearnersdictionaries.com/wordlists/oxford3000-5000">Oxford 3000 and 5000 | OxfordLearnersDictionaries.com</a>
        </dt><dt><a href="https://www.oxfordlearnersdictionaries.com/about/wordlists/">About Word Lists at Oxford Learner's Dictionaries | OxfordLearnersDictionaries.com</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">Longman Communication 3000 and 9000</h3>
    <dl><p>
        </p><dt><a href="http://sope.ruc.edu.cn/displaynews.php?id=930">Longman Communication 3000</a>
        </dt><dt><a href="https://github.com/sapbmw/Longman-Communication-3000">sapbmw/Longman-Communication-3000: Longman Communication 3000 word list, English Words List - Learn English Words</a>
        </dt><dt><a href="https://www.pdawiki.com/forum/forum.php?mod=viewthread&amp;tid=18669&amp;highlight=LONGMAN">Longman Communication 9000 from LDOCE6 -  PDAWIKI</a>
        </dt><dt><a href="https://github.com/iokays/longman-communication-9000">Longman Communication 9000</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">google 10000</h3>
    <dl><p>
        </p><dt><a href="https://github.com/first20hours/google-10000-english">google-10000-most common english words</a>
        </dt><dt><a href="https://books.google.com/ngrams">Google Ngram Viewer</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">Longman Defining Vocabulary</h3>
    <dl><p>
        </p><dt><a href="https://www.frathwiki.com/Longman_Defining_Vocabulary/alphabetically" add_date="1556182653">Longman Defining Vocabulary/alphabetically - FrathWiki</a>
        </dt><dt><a href="http://www2.cmp.uea.ac.uk/~jrk/conlang.dir/LongmanVocab.html" add_date="1556182712">The Longman Defining Vocabulary</a>
        </dt><dt><a href="https://www.frathwiki.com/Longman_Defining_Vocabulary" add_date="1556182721">Longman Defining Vocabulary - FrathWiki</a>
        </dt><dt><a href="https://www.frathwiki.com/Category:Longman_Defining_Vocabulary" add_date="1556183052">Longman Defining Vocabulary - FrathWiki</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">Macmillan Dictionary Common English Words</h3>
    <dl><p>
        </p><dt><a href="https://www.macmillandictionary.com/learn/red-words.html">Macmillan Dictionary Common English Words</a>
        </dt><dt><a href="https://www.macmillandictionary.com/learn/english-language-resources.html">English Language Resources from Macmillan Dictionary</a>
    </dt></dl><p>
    </p></dt><dt><h3 add_date="1594629314" last_modified="1594629314">Famous Freq Lists - Lextutor.ca</h3>
    <dl><p>
        </p><dt><a href="https://www.lextutor.ca/freq/lists_download/">Famous Freq Lists - Lextutor.ca</a>
        </dt><dt><a href="https://www.lextutor.ca/">Compleat Lexical Tutor</a>
    </dt></dl><p>
    </p></dt><dt><a href="http://www.manythings.org/voa/words.htm">VOA Special English Word Book</a>
    </dt><dt><a href="https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings" add_date="1550587172">Wikipedia:Lists of common misspellings - Wikipedia</a>
    </dt><dt><a href="https://hypcol.marutank.net/" add_date="1554795383">Hyper Collocation — dictionary based on arXiv repository</a>
    </dt><dt><a href="http://ling.cuc.edu.cn/RawPub/" add_date="1554795486">媒体语言语料库(MLC)</a>
    </dt><dt><a href="http://www.anc.org/">Open American National Corpus | Open Data for Language Research and Education</a>
    </dt><dt><a href="http://www2.cmp.uea.ac.uk/~jrk/conlang#Misc" add_date="1556182614">Richard Kennaway's Constructed Languages List</a>
    </dt><dt><a href="https://www.frathwiki.com/Mills_Basic_Vocabulary" add_date="1556182760">Mills Basic Vocabulary - FrathWiki</a>
    </dt><dt><a href="https://en.m.wikipedia.org/wiki/Basic_English" add_date="1556191464">Basic English - Wikipedia</a>
    </dt><dt><a href="https://github.com/jjzz/ZZ-WordFreq">jjzz/ZZ-WordFreq: words frequency top100k from BNC/ANC/COCA, dsl format, for goldendict</a>
    </dt><dt><a href="https://www.pdawiki.com/forum/forum.php?mod=viewthread&amp;tid=13348">[2016.4.26更新]17万词BNC+ANC+COCA词频词典</a>
    </dt><dt><a href="https://www.pdawiki.com/forum/forum.php?mod=viewthread&amp;tid=31168&amp;ctid=291">更新 Word Frequency of 170,000 Words</a>
    </dt><dt><a href="http://www.just-the-word.com/">Just The Word 搭配使用频率</a>
</dt></dl><p>
</p>

**Comment by BlindingDark** [comment]
@VimWei 尽量发些无版权疑问的，程序能处理的词库来源，比如一些大学使用的学习资料，我们应该是无权直接拿来用的，而且一些是 pdf 格式的，不方便进行处理。麻烦整理一个筛选过后的列表。

**Comment by VimWei** [comment]
专业词库： https://pinyin.sogou.com/dict/
专业词典： https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=42412

**Comment by BlindingDark** [comment]
> 专业词库： https://pinyin.sogou.com/dict/
> 专业词典： https://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=42412

1. 无版权
2. 无法处理

**Comment by VimWei** [comment]
> @VimWei 尽量发些无版权疑问的，程序能处理的词库来源，比如一些大学使用的学习资料，我们应该是无权直接拿来用的，而且一些是 pdf 格式的，wiki 连接之类的，这些都不方便进行处理。麻烦整理一个筛选过后的列表。

恩，上述纯粹就是我的浏览器书签导出的，确实未作整理。不过，我们没有必要把所有可用的资料都处理成现成的词库。

建议：给出一两个典型的词库案例，提供使用自定义词库的机制、如何自定义词库的教程等，其他的就让用户自己想办法解决即可。

**Comment by BlindingDark** [comment]
> 使用自定义词库的机制、如何自定义词库的教程

普通用户没有这个能力和精力

**Comment by VimWei** [comment]
纯粹开源、无版权的资料，确实少之又少。使用效果也不好。

还是忽略上述资料吧，它们仅作为解释说明：什么是词频语料库、什么是专业词库。

PS：使用Rime的用户，估计都喜欢折腾。。。不能定义为普通用户。。。我曾经下载过，放弃了，这两天才又捡起来。。。

**Comment by BlindingDark** [comment]
> 纯粹开源、无版权的资料，确实少之又少

ECDICT 是我能找到的最靠谱的开源词库了，可以围绕它来做几个裁剪和修补。

**Comment by VimWei** [comment]
还有wiktionary。

忘了从哪看到的，有人将Wikipedia的词头作为来源，定期更新。

**Comment by blackhole889** [comment]
rime是一个很好的输入法程序，但也存在一些较大的不足。其中一个就是词库的建立和精选。
提高词库的效率有两个两个方法，我需要的在里面，我不需要的不在里面。只关注其一，如加大词库数量无法提高词库的效率。
现在rime似乎无法删除一些已有词库里的词（其宣称的ctr+del，shift+del,ctr+k可以删除自造词，无法删除一些词库里的词，甚止降低已有词库权重也难以做到。降低已有词库权重偶而可以做到，很不稳定）。有些词一般用户用不到，如果从词库删除可以加大输入效率。能否对原有程序进行修改，使得可以删除任意词组。

解决词库里删除词语问题，也可以让用户删除一些个人隐私词语，共享出个人词库，从而精炼出好的词库。

**Comment by BlindingDark** [comment]
> 能否对原有程序进行修改

不在本 issue 讨论范围之内。请去 rime 那边反馈意见。
