### ISSUE TITLE
The option 'translator/enable_sentence: true' in easy_en.yaml is useless.

### ISSUE THREAD

**Issue by Titubery** [BlindingDark/rime-easy-en#2]
I am not sure what that means for easy_en but it only activates taij [☯️️] icon for wubi or cangjie sentence input, however, I just use pinyin schema on ibus-rime.
![Screenshot from 2019-10-15 14-12-38](https://user-images.githubusercontent.com/17917040/66804835-19c3d080-ef56-11e9-8cb0-87421c783caf.png)

**Comment by BlindingDark** [comment]
It may help to input some words that are not in the dictionary when using double_pinyin or else.

For example, typing `vimcfg` in double_pinyin

`translator/enable_sentence: true`:

![image](https://user-images.githubusercontent.com/13600799/66808179-45968480-ef5d-11e9-87ff-d125acf0eb58.png)

`translator/enable_sentence: false`:

![image](https://user-images.githubusercontent.com/13600799/66808216-5a731800-ef5d-11e9-9799-89a59166ebcd.png)

**Comment by Titubery** [comment]
So that's it. I just use luna_pinyin and consider that may be a flaw in design. Thanks!

**Comment by tp20c5** [comment]
建议关闭之。双拼设置取消自动扩展后不会影响生词输入的视觉指示。不过有趣的是当重复输入自定义短语时，仍然会指示☯️符号。

![Image](https://github.com/user-attachments/assets/bfc324b1-4675-414b-84f4-17b55a48f30a)

```
patch:
  #取消双拼自动扩展
  'translator/preedit_format': []
```
