### ISSUE TITLE
连续输入时输入框能自动分词，选词框还是没有空格

### ISSUE THREAD

**Issue by fratcn** [BlindingDark/rime-easy-en#20]
比如I love rime
输入框显示单词之间有空格，选词框却还是Iloverime
什么原因，怎么解决？

**Comment by BlindingDark** [comment]
和 readme 中的动图预览效果一样么?

**Comment by fratcn** [comment]
输入框是一样的：I love rime
选词框不一样，只有Iloverime

**Comment by BlindingDark** [comment]
readme 中动图展示的效果是，五项候选，绿色框框中的英文，有灯泡💡的选项是加了空格的，而光标输入的地方是没有加空格的，你那边也是这个效果么？

**Comment by fratcn** [comment]
截图链接：
[](https://github.com/fratcn/fratcn.github.io/blob/master/images/2020-12-20_22-49-45.png)

**Comment by BlindingDark** [comment]
看起来并没有成功开启自动分词，成功的话会有灯泡💡的提示。
有没有使用最新版的 easy-en 呢，可以尝试升级到最新版试试。

**Comment by BlindingDark** [comment]
如果没有其它疑问的话，暂时先把这个 issue 关闭了，如果还有问题欢迎继续留言😘

**Comment by HLeonHong** [comment]
我想请教下，我用的是五笔的，输入框没有空格分词，我该在哪里修改哪些内容呢呢？
