### ISSUE TITLE
使用 Rust 移植版本的 WordNinja

### ISSUE THREAD

**Issue by chengyuhui** [BlindingDark/rime-easy-en#21]
我尝试对 WordNinja 使用 Rust [进行了移植](https://github.com/chengyuhui/wordninja-rs)，目前已经可以通过原有项目自带的全部单元测试。

我在编译时就把词库读取进了程序（同样支持自定义词库），所以命令行调用时不会有任何额外的文件IO，后面也可以考虑做成Lua DLL（不清楚 Rime 那边能否支持这一功能），初步测试比原有版本快 7 倍以上。

**Comment by BlindingDark** [comment]
Lua DLL 挺起来是 Windows 专属的功能？有进一步说明么？

**Comment by chengyuhui** [comment]
Lua 可以直接加载按照特定方式编译的动态链接库 （DLL/so/dylib），这样可以省掉每次读取可执行文件和构建 cost map 的时间，不过我还需要再研究一下

现在这个二进制应该其实足够快了，但是还需要想个办法编译出可执行文件然后分发（毕竟我们没有 pip，虽然可以 `cargo install`，但 Rust 的工具链太重了）

**Comment by BlindingDark** [comment]
已经完善了相关的配置以及文档，加了一个 [AUR 仓库](https://aur.archlinux.org/packages/wordninja-rs/)，别的平台的分发问题我们可以在 wordninja-rs 那边继续讨论，这个 Issue 暂时先关闭了。

如果有什么问题欢迎再讨论😘
