### ISSUE TITLE
和地球拼音terra_pinyin的兼容性问题

### ISSUE THREAD

**Issue by nullmax** [BlindingDark/rime-easy-en#25]
比如我想输入Fast，依次按Shift+F，a，s，t
在没加载easy_en时，地球拼音的表现是正常的，Fast是可以连续输入，然后一并输出
加载easy_en后，按下Shift+F后，直接就把F输出了，后面的ast连不上了。
luna_pinyin就没有这个问题，有什么设置能解决呢？

**Comment by BlindingDark** [comment]
感谢反馈

最新的版本已经修复，想要应用此次升级修复
1. 若你使用 `plum` 进行安装，则只须重新执行安装命令
    ```bash
    bash rime-install BlindingDark/rime-easy-en:customize:schema=terra_pinyin
    ```
2. 若你是手动配置，首先下载最新版本的 easy-en，接下来需要修改 `terra_pinyin.custom.yaml` 文件中的 `patch` 节点如下即可
    ```yaml
    patch:
        __include: easy_en:/patch_terra_pinyin
    ````

如仍有问题欢迎继续沟通😘
---

相关 issue

https://github.com/rime/rime-terra-pinyin/issues/36
