### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Pantyhose-X** [BlindingDark/rime-easy-en#29]
你好 可以增加这种功能吗？

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

TTS朗读输入
应用于语言学习。发音纠正，这样可以纠正发音和加深记忆，
母语不是英语。需要学习英语，市场非常大

**Comment by BlindingDark** [comment]
PR is welcome.
