### ISSUE TITLE
easy_en.dict.yaml 数据损坏

### ISSUE THREAD

**Issue by Ace-Who** [BlindingDark/rime-easy-en#3]
有 12 处大量连续重复的 `\0` 字符，原数据本应是大量单词条目，例如以 k 开头的单词全部缺失。

**Comment by BlindingDark** [comment]
是有这样的问题。不过我没找到合适的词库。
有没有推荐的词库呢？目前的词库版本来源未知，而且可能比较老旧了。
如果能换上更全更完善的词库就太好了。

**Comment by Ace-Who** [comment]
我没找过，不太了解。

**Comment by BlindingDark** [comment]
https://github.com/skywind3000/ecdict
计划采用 ecdict 生成一份出来

**Comment by BlindingDark** [comment]
@Ace-Who https://github.com/BlindingDark/rime_easy_eng_dict
生成出来有 22 MB，比较大，我考虑先搞出一个精简版再传上来。然后提供一个手动下载词典的方式。

**Comment by BlindingDark** [comment]
@Ace-Who 已更新完毕。我只挑了有词频的单词，出来的结果 4M 大小，效果还不错。
完整版太大了，加载和相应都比较慢，以后考虑整理出来一个，发布到那边的项目，供用户自行下载。

这个 issue 我先关闭了，有啥问题再说。

**Comment by Ace-Who** [comment]
好的。
