### ISSUE TITLE
很奇怪的置顶词条无法删除：buts、yu、vs等

### ISSUE THREAD

**Issue by VimWei** [BlindingDark/rime-easy-en#32]
我在windows 10中使用rime + easy_en + 小鹤双拼，中英混输

只要我启用easy_en，就会出现一个置顶词汇 'buts'，鉴于这个在小鹤双拼里是超高频词汇‘不同’的双拼，很是烦人，不知道该如何删除？我已经排查过easy_en.dict.yaml，其中没有这个词汇，即使将其整个清空，依然会出现 buts 这个置顶词。

还有部分词汇与此情形类似，比如”与“对应的拼音”yu“，以及”中“对应的双拼”vs“。

我遍寻词库，就是不知道该如何删除它们。还请指教。

**Comment by BlindingDark** [comment]
来个截图？

**Comment by VimWei** [comment]
## 当取消混输：
![image](https://user-images.githubusercontent.com/25874852/150922400-e0e63432-9fa9-4a28-9514-90647cd268a2.png)
输入正常：
![image](https://user-images.githubusercontent.com/25874852/150922329-ddb198ed-da94-420c-8937-b08de3e9d617.png)

## 当启用混输：
![image](https://user-images.githubusercontent.com/25874852/150922504-4b48cac2-3a76-40de-866f-d57a8bd25184.png)
会出现不知如何删除的置顶词条（它们不在easy_en.dict.yaml）：
![image](https://user-images.githubusercontent.com/25874852/150922668-c0a95248-8ab3-4e54-847d-a6d4aca69687.png)

**Comment by VimWei** [comment]
找到问题所在了，是用户数据easy_en.userdb的问题。
