### ISSUE TITLE
连续输入时输入框不能自动分词，没有小灯泡，选词框也没有空格

### ISSUE THREAD

**Issue by HLeonHong** [BlindingDark/rime-easy-en#34]

**Comment by HLeonHong** [comment]
已经解决。
我是手动安装的，下载好的**lua**文件夹是放在用户文件夹的，不放在**程序文件夹**，这样就能呼出小灯泡了

**Comment by BlindingDark** [comment]
Hello，你可以附上你是怎么解决的，这样可以帮助到和你有相同问题的人🙏🏻

**Comment by HLeonHong** [comment]
> 

好，主要是一些注意事项。我这些天整理上来。

对了，是不是暂时不支持“ ' ”的情况（所有格）例如：
teacher's
teachers'
在输入的过程中，输入了，但候选框却没显示
![Snipaste_2022-09-29_22-57-32](https://user-images.githubusercontent.com/44226142/193067171-ca099b99-1ca7-4e77-9220-886ceb3943a5.png)
![Snipaste_2022-09-29_22-58-35](https://user-images.githubusercontent.com/44226142/193067180-d3d9e811-c3a9-4893-9017-bd6dc866a681.png)
