### ISSUE TITLE
如何限制easy en建议的词条数量

### ISSUE THREAD

**Issue by fhfuih** [BlindingDark/rime-easy-en#38]
如题。有时候建议的英文数量太多了，反而要翻页好多次才能找到想要的中文词条。

**Comment by BlindingDark** [comment]
目前只能修改权重，效果还凑合吧，基本上可以让中文优先出来。

**Comment by fhfuih** [comment]
好吧，谢谢😂 确实文档里面没找到相关的所以才发的issue，那我先关闭了
