### ISSUE TITLE
双拼中英文混输的问题

### ISSUE THREAD

**Issue by wongdean** [BlindingDark/rime-easy-en#9]
你好，我按照提示将我自己的双拼集成了混输的功能，具体来说是，在`double_pinyin_flypy.custom.yaml`后增加几行：
```
__patch:
  - patch/+:
      __include: easy_en:/patch
```
但是无法像朙月拼音那样，在键入带有英文的句子中出现英文候选，如：
键入：woxihrschool
候选时，还是将school识别为两个三个词，即 sc ho l
请问这种是我理解错了，还是配置问题呀？

配置朙月拼音方案时，一切正常，非常棒！

**Comment by wongdean** [comment]
![TSoBg8](https://wang-1258168870.cos.ap-guangzhou.myqcloud.com/TSoBg8.png)

**Comment by BlindingDark** [comment]
先把前几个字(wo xi hr)选出来，等到了 school 的时候应该就会出现了。但是默认的英文排序会比较靠后，你可能要往后翻个几页才能看到。

**Comment by BlindingDark** [comment]
@wongdean 将优先级调高的话能出现英文单词候选了么？

**Comment by wongdean** [comment]
刚才我试了一下，我的候选里面没有出现 school，估计可能是因为我们自定义设置的问题。我的配置文件在我的项目中：https://github.com/wongdean/rime-settings

请问您方便把您的双拼配置文件发我一份吗？除词库外的其他文件，我研究一下到底为什么。
wang.deans@hotmail.com
或者，telegram: shiyuan19

**Comment by BlindingDark** [comment]
看了你的配置之后发现这个配置有误，删掉即可

```
patch:
  schema/dependencies: {}
```
